FROM python:3.6
COPY . /docker_api
WORKDIR /docker_api
RUN apt-get update \
    && apt-get install -y \
        build-essential \
        cmake \
        git \
        wget \
        unzip \
        yasm \
        pkg-config \
        libswscale-dev \
        libtbb2 \
        libtbb-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libavformat-dev \
        libpq-dev 
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["App.py"]
